services:
  - type: web
    name: importacion-costos-api
    runtime: docker
    plan: free
    region: ohio
    autoDeploy: false
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: APP_WEB_ALLOWED_ORIGINS
        value: https://arancel593.web.app,https://arancel593.firebaseapp.com
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: JDBC_DATABASE_URL
        sync: false
